# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ELEC522/GIM/GIM-2024-2025/gim_cpp_final/project_2/project_2.srcs/sources_1/bd/design_1/ip/design_1_accelerator_0_0/design_1_accelerator_0_0.xci
# IP: The module: 'design_1_accelerator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ELEC522/GIM/GIM-2024-2025/gim_cpp_final/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_accelerator_0_0/constraints/accelerator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_accelerator_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/ELEC522/GIM/GIM-2024-2025/gim_cpp_final/project_2/project_2.srcs/sources_1/bd/design_1/ip/design_1_accelerator_0_0/design_1_accelerator_0_0.xci
# IP: The module: 'design_1_accelerator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ELEC522/GIM/GIM-2024-2025/gim_cpp_final/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_accelerator_0_0/constraints/accelerator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_accelerator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
