domain_path: C:\GIM\hls_ltr\platform\export\platform\sw\standalone_psu_cortexa53_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
