set_property PACKAGE_PIN B14 [get_ports {alpha_transmit_line_0[0]}]
set_property PACKAGE_PIN D15 [get_ports alpha_transmit_line_ap_vld_0]
set_property PACKAGE_PIN G13 [get_ports alpha_transmit_line_ap_ack_0]
set_property IOSTANDARD LVCMOS18 [get_ports {alpha_transmit_line_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports alpha_transmit_line_ap_ack_0]
set_property IOSTANDARD LVCMOS18 [get_ports alpha_transmit_line_ap_vld_0]
